spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:production}